# SITE SETTINGS
title: Structured Descriptive Data
url: "https://sdd.tdwg.org"

# SOCIAL PROFILES
social:
  github: tdwg/sdd

# THEME SETTINGS
theme: minima
remote_theme: tdwg/petridish
github_edit: false
logo: /assets/theme/images/tdwg-logo-short.svg

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: ""
    values:
      layout: default
      toc: true
